### PR TITLE
Added embedded codes

### PR DESCRIPTION
**Pull request by tzikis**
@aethaniel please do not merge yet, this is a work in progress

we will ping you tomorrow when it's ready for merging 👍

### CODE REVIEW

**Comment by freskoulix** [comment]
@aethaniel this is ready for merge.
(cc: @tzikis)

**Comment by aethaniel** [comment]
I tested this PR on a local branch and I see both iframes empty. 
A quick drawn Blockly sketch worked perfectly on an atmega328p-xmini with optiboot bootloader.

**Comment by tzikis** [comment]
Hey Thibaut,
That makes sense, the iframe unfortunately needs to use a whitelist of domains it works with, so if you test it locally you'll have to make an alias of atmeluniversityfrance.github.io to 127.0.0.1 for the code auto-loading to work

**Comment by aethaniel** [comment]
oki doki, I merge and we will see :smile:

**Comment by freskoulix** [comment]
Just checked and it seems :+1:

**Pull request merged**
